sudo: required
services:
  - docker

before_install:
  - docker build -t mcfisch/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mcfisch/react-test npm test

after_success:
  - docker build -t mcfisch/multi-client ./client
  - docker build -t mcfisch/multi-nginx ./nginx
  - docker build -t mcfisch/multi-server ./server
  - docker build -t mcfisch/multi-worker ./worker
  # Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mcfisch/multi-client
  - docker push mcfisch/multi-nginx
  - docker push mcfisch/multi-server
  - docker push mcfisch/multi-worker
